/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import AppPackage.AnimationClass;

/**
 *
 * @author Tanmay
 */
public final class quiz2 extends javax.swing.JFrame {

    /**
     * Creates new form quiz2
     */
    AnimationClass a=new AnimationClass();

    /**
     *
     */
    public quiz2() {
        initComponents();
         setSize(600,600);
         slide();
       
    }
    public final void slide()
    {
        new Thread()
        {
            @Override
            public void run()
            {
       try
       {
           while(true)
        {
        a.jLabelXLeft(0, -600, 12, 2, jLabel4);
        a.jLabelXLeft(600, 0, 12, 2, jLabel3);
        a.jButtonYDown(0, 450, 14, 2, jButton1);
        try
        {
            Thread.sleep(1000);
            a.jLabelXRight(-600, 0,12, 2, jLabel4);
             a.jLabelXRight(0, 600, 12, 2, jLabel3);
             Thread.sleep(4000);
             a.jLabelYUp(0, -600, 12, 2, jLabel3);
             a.jLabelYUp(600, 0, 12, 2, jLabel5);
             break;
            // a.jLabelXRight(, 600, 12, 2, jLabel3);
             
        }
        catch(Exception m)
        {
            
        }
        }
    }
        catch(Exception e)
        {
        }
    }
    }.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("congrats you won!!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 130, 350, 39);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("next");
        jButton1.setDefaultCapable(isUndecorated());
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 0, 80, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("100 points!!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 250, 180, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/black_background_pattern_light_texture_55291_1920x1200.jpg"))); // NOI18N
        jLabel4.setAlignmentY(0.0F);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 600, 600);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/aerial_photography_toronto_black_and_white-wallpaper-1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(600, 0, 600, 600);

        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\wallpapers n themes\\my photos\\battlefield_47-wallpaper-1920x1080.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 600, 600, 600);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 quiz4 ob1=new quiz4();
 ob1.setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new quiz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
