 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import AppPackage.AnimationClass;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;

/**
 *
 * @author Tanmay
 */
public class quiz1 extends javax.swing.JFrame {

    /**
     * Creates new form quiz1
     */
     AnimationClass ac=new AnimationClass();
        
    public quiz1()
    {
        initComponents();
        setSize(600,600);
       slideshow();
        
       // jLabel3.setText(uname);
    }
   
     public final  void slideshow()
    {
        
       
        new Thread()
        {
            int c=0;
            @Override
            public void run()
            {
                 
                
                
                while(true)
                {
               
                    switch(c)
                    {
                        case 0:
                         
                           ac.jLabelXRight(-55, 100, 6, 2, jLabel1);
                            ac.jLabelXLeft(570, 150, 6, 2, jLabel4);
                           try
                            {
                               Thread.sleep(2000);
                                
                            }
                            catch(InterruptedException ex) {
                               
                                
                                    
                                }
                             ac.jButtonXRight(0, 230, 10,2, jButton1);
                             try
                            {
                               Thread.sleep(3000);
                                
                            }
                            catch(InterruptedException ex) {
                               
                                
                                    
                                }
                             
                            ac.jLabelXLeft(0, -1200, 12, 2, jLabel5);
                            ac.jLabelXLeft(600, -600, 12, 2, jLabel3);
                            ac.jLabelXLeft(1200, 0, 12, 2, jLabel6);
                            
                           
                           
                             
                             
                              
                              // ac.jLabelYUp(600,0, 12, 2, jLabel7);
                            
                           
                            
                             // ac.jButtonXLeft(530, 230, 150, 10, jButton1);
                           // ac.jLabelYUp(0,-600, 100, 10, jLabel6);
                            
                           c=1;
                           
                            break;
                        case 1:
                    
                    
                        ac.jLabelXRight(-1200, 0, 100, 10, jLabel5);
                         ac.jLabelXRight(-600, 600, 100, 10, jLabel3);
                         ac.jLabelXRight(0, 1200, 100, 10, jLabel6);
                   c=0;
                        break;
                    }
                   
                    
                  
                                
                                
                                
                               
                                
                                
                                
                                
                            }
                        
                 
                    }
                    
                    
               
               
            }.start();
            

    }
            
       
    
    

    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel8.setIcon(new javax.swing.ImageIcon("F:\\wallpapers n themes\\stock-vector-circles-background-with-lines-quiz-icons-human-brain-think-checklist-and-stopwatch-timer-symbol-253040155.jpg")); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\wallpapers n themes\\stock-vector-circles-background-with-lines-quiz-icons-human-brain-think-checklist-and-stopwatch-timer-symbol-253040155.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("hello ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-55, 10, 82, 42);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("welcome !!!");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 30, 191, 50);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Garamond Premr Pro Smbd", 2, 36)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 204, 51));
        jTextArea1.setRows(5);
        jTextArea1.setTabSize(10);
        jTextArea1.setText("Q.1  who plays the role of harry potter in\n the    harry potter movie series ?");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 104, 550, 130);

        jRadioButton1.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 255, 0));
        jRadioButton1.setText("JJ.K.Rollings");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton1.setBorderPainted(true);
        jRadioButton1.setDisabledSelectedIcon(new javax.swing.ImageIcon("F:\\wallpapers n themes\\pic\\KinderCare   Child Daycare Centers & Early Education Programs_files\\summer_01_310x215.jpg")); // NOI18N
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(60, 290, 160, 30);

        jRadioButton2.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 255, 0));
        jRadioButton2.setText("Rupert Grint");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton2.setBorderPainted(true);
        jRadioButton2.setDisabledSelectedIcon(new javax.swing.ImageIcon("F:\\wallpapers n themes\\pic\\KinderCare   Child Daycare Centers & Early Education Programs_files\\summer_01_310x215.jpg")); // NOI18N
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(350, 290, 150, 30);

        jRadioButton3.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 255, 0));
        jRadioButton3.setText("Daniel Radcliffe");
        jRadioButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton3.setBorderPainted(true);
        jRadioButton3.setDisabledSelectedIcon(new javax.swing.ImageIcon("F:\\wallpapers n themes\\pic\\KinderCare   Child Daycare Centers & Early Education Programs_files\\summer_01_310x215.jpg")); // NOI18N
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(60, 410, 160, 30);

        jRadioButton4.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(0, 255, 0));
        jRadioButton4.setText("Emma Watson");
        jRadioButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton4.setBorderPainted(true);
        jRadioButton4.setDisabledSelectedIcon(new javax.swing.ImageIcon("F:\\wallpapers n themes\\pic\\KinderCare   Child Daycare Centers & Early Education Programs_files\\summer_01_310x215.jpg")); // NOI18N
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(350, 410, 150, 30);

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("LOCK");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 497, 90, 33);

        jButton2.setText("time");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 10, 53, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\wallpapers n themes\\stock-vector-circles-background-with-lines-quiz-icons-human-brain-think-checklist-and-stopwatch-timer-symbol-253040155.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 600, 600);

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\wallpapers n themes\\math-magic-hd-wallpapers.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(600, -30, 600, 600);

        jLabel6.setIcon(new javax.swing.ImageIcon("F:\\wallpapers n themes\\4dcdb524774585ff408e42feb960ec8e_1024.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1200, -20, 600, 600);

        jLabel7.setIcon(new javax.swing.ImageIcon("F:\\wallpapers n themes\\battlefield_47-wallpaper-1920x1080.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1200, 600, 600, 600);

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(700, 340, 90, 40);

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 220, 530, 220);

        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(290, 160, 180, 80);

        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(480, 140, 70, 80);

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
quiz2 ob =new quiz2();
quizw ob1=new quizw();
        if(jRadioButton3.isSelected())
        {
            ob.setVisible(true);
            dispose();
        }// TODO add your handling code here:
        else if(jRadioButton1.isSelected())
        {
        ob1.setVisible(true);
        dispose();
        }
        else if(jRadioButton2.isSelected())
        {
        ob1.setVisible(true);
        dispose();
        }
        else if(jRadioButton4.isSelected())
        {
        ob1.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new quiz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
