/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import AppPackage.AnimationClass;
import javax.swing.ImageIcon;

/**
 *
 * @author Tanmay
 */
public class quiz5 extends javax.swing.JFrame {

    /**
     * Creates new form quiz5
     */
    AnimationClass a =new AnimationClass();
    public quiz5() {
        initComponents();
        setSize(600,600);
        slide4();
    }

      public final void slide4()
    {
        new Thread()
        {
            int c=0;
            @Override
            public void run()
            {
       try
       {
           while(true)
        {
           // a.jButtonYDown(0, 450, 14, 2, jButton1);
            switch(c)

            {
                
        case 0:
             
        
                
        a.jLabelXLeft(0, -600, 12, 2, jLabel2);
        a.jLabelXLeft(600, 0, 12, 2, jLabel3);
        
         try
        {
            Thread.sleep(5000);
            ImageIcon i1 =new ImageIcon(getClass().getResource("/ipack/gold-wallpaper-18[-12654.jpg"));
                  jLabel2.setIcon(i1);
    }
           
        
        catch(Exception m)
        {
            
        }
     
        c=1;
        break;
        
        case 1:
             
        
             a.jLabelXRight(-600, 0,12, 2, jLabel2);
             a.jLabelXRight(0, 600, 12, 2, jLabel3);
           
              
                 try
        {
            Thread.sleep(5000);
            ImageIcon i2 =new ImageIcon(getClass().getResource("/ipack/Blue-Background-Rain-Wallpaper1.jpg"));
                  jLabel3.setIcon(i2);
    }
           
        
        catch(Exception m)
        {
            
        }
                  c=2;
             break;
              case 2:
        
                 
        a.jLabelXLeft(0, -600, 12, 2, jLabel2);
        a.jLabelXLeft(600, 0, 12, 2, jLabel3);
        a.jButtonYDown(0, 450, 14, 2, jButton1);
        Thread.sleep(5000);
        ImageIcon i3 =new ImageIcon(getClass().getResource("/ipack/quiz_#22 61735_4eb93979ac21-2ff8-f774-ff32-e61ff4a1-1gedn8e56cb5bk00t7gi5wii.jpg"));
                  jLabel2.setIcon(i3);
     
        c=3;
        break;
         case 3:
        
             a.jLabelXRight(-600, 0,12, 2, jLabel2);
             a.jLabelXRight(0, 600, 12, 2, jLabel3);
           
              
                 try
        {
            Thread.sleep(5000);
              ImageIcon it3=new ImageIcon(getClass().getResource("/ipack/battlefield_47-wallpaper-1920x1080.jpg"));
                  jLabel3.setIcon(it3);
    }
           
        
        catch(Exception m)
        {
            
        }
                  c=0;
             break;
            
            
        
        
    }
        }
    }
        catch(Exception e)
        {
        
    
        }
            }
    }.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("200 points !!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 60, 195, 33);

        jTextArea1.setBackground(new java.awt.Color(204, 255, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText(" Q3.For which of the following discipl-\n   ines is Nobel Prize awarded?");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 118, 578, 112);

        jRadioButton1.setBackground(new java.awt.Color(102, 255, 51));
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(153, 255, 255));
        jRadioButton1.setText(" [A]Physics and Chemistry");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(80, 250, 360, 30);

        jRadioButton2.setBackground(new java.awt.Color(102, 255, 51));
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(153, 255, 255));
        jRadioButton2.setText("[B].Physiology or Medicine");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(80, 300, 360, 30);

        jRadioButton3.setBackground(new java.awt.Color(102, 255, 51));
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(153, 255, 255));
        jRadioButton3.setText("[C].Literature, Peace and Economics");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(80, 350, 360, 30);

        jRadioButton4.setBackground(new java.awt.Color(102, 255, 51));
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(153, 255, 255));
        jRadioButton4.setText("[D].All of the above");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(80, 400, 366, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jButton1.setText("Lock it");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 450, 101, 37);

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\wallpapers n themes\\background_stack0300.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 600);

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\wallpapers n themes\\my photos\\fresh_green_grass_7-wallpaper-2560x1440.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(600, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
quiz6 ob =new quiz6();
quizw ob11=new quizw();
        if(jRadioButton4.isSelected())
        {
            ob.setVisible(true);
            dispose();
        }// TODO add your handling code here:
        else if(jRadioButton1.isSelected())
        {
        ob11.setVisible(true);
        dispose();
        }
        else if(jRadioButton3.isSelected())
        {
        ob11.setVisible(true);
        dispose();
        }
        else if(jRadioButton2.isSelected())
        {
        ob11.setVisible(true);
        dispose();
        }        // TODO add yo        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quiz5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quiz5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quiz5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiz5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quiz5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
